version: '3'

services:
  db:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: letters
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    depends_on:
      - 'db'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
