version: '3'

services:
  db:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: letters
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    depends_on:
      - 'db'
      - 'webpacker'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - '.:/app'
    ports:
      - '3035:3035'

