default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  database: trump_development
  username: letters
  password: password
  port: 5432

development:
  <<: *default

test:
  <<: *default
  database: trump_test
